FROM python:3.8.2-alpine
WORKDIR /usr/src/app

RUN apk update && apk add \
        build-base \
        libffi-dev \
        openssl \
        openssl-dev

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT [ "python", "./auto_cert_gen_client.py" ]
